# Generated by Django 4.2.2 on 2023-07-15 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_branch_is_central'),
        ('city', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branch.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_central',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
