# Generated by Django 4.2.2 on 2023-08-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order_id',
            new_name='product_id',
        ),
    ]
