# Generated by Django 4.2.2 on 2023-09-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_order_id_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cash_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='non_cash_sales',
            field=models.IntegerField(default=0),
        ),
    ]
