# Generated by Django 4.2.2 on 2023-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_firstperiodproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_installments_mounth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='max_installments_mounth',
            field=models.IntegerField(default=0),
        ),
    ]
