# Generated by Django 4.2.2 on 2023-09-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_discount_installments_mounth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_installments_mounth',
            new_name='discount_installments_month',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='max_installments_mounth',
            new_name='max_installments_month',
        ),
    ]
