# Generated by Django 4.2.2 on 2023-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('مدیر کل', 'مدیر کل'), ('مدیر فروش', 'مدیر فروش'), ('مدیر استان', 'مدیر استان'), ('مدیر شعبه', 'مدیر شعبه'), (' فروشنده', ' فروشنده'), ('حسابدار', 'حسابدار')], max_length=256, null=True),
        ),
    ]
