# Generated by Django 4.2.2 on 2023-07-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('مدیر کل', 'مدیر کل'), ('مدیر فروش', 'مدیر فروش'), ('مدیر استان', 'مدیر استان'), ('مدیر شعبه', 'مدیر شعبه'), ('فروشنده', 'فروشنده'), ('حسابدار', 'حسابدار')], max_length=256, null=True),
        ),
    ]
