# Generated by Django 4.2.2 on 2023-07-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
