# Generated by Django 4.2.2 on 2023-07-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_branch_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_central',
            field=models.BooleanField(default=False),
        ),
    ]
