# Generated by Django 4.2.2 on 2023-09-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('branch', '0004_branch_is_central'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.city'),
        ),
    ]
